default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  database: clone_instagram_rails_development

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  database: clone_instagram_rails_test

production:
  <<: *default
  database: clone_instagram_rails_production
  username: clone_instagram_rails
  password: <%= ENV['CLONE_INSTAGRAM_RAILS_DATABASE_PASSWORD'] %>
